adding Home_work8/Home_work8.cpp
Myroslav229/Home_Work pull request #8
Opened 2023-07-15 18:35 UTC by Myroslav229

pushing to github

2023-07-24 18:33 UTC, bohdanpc requested changes

2023-07-24 18:33 UTC, bohdanpc commented on Home_work8/Home_work8.cpp
> +        if (str[i] != str[strlen(str) - 1 - i])
better call strlen() once outside of the loop since it's costly operation

2023-07-24 18:33 UTC, bohdanpc commented on Home_work8/Home_work8.cpp
> +bool isEqual(const char str1[], const char str2[]) {
This function won't work. Please check it thorougly

2023-08-16 07:42 UTC, helen-black approved these changes

2023-08-16 07:42 UTC, merged